export const SYNC_STATE_KEY = '@@SYNC_STATE';
export const SYNC_STORAGE_KEY = '@@SYNC';
export const SYNC_MUTATION_KEY = '@@SYNC_MUTATION';
export const SYNC_RECONNECT_MUTATION_KEY = '@@SYNC_RECONNECT_MUTATION';
